### ISSUE TITLE
Do you know the folks doing the PHP C module?

### ISSUE THREAD

**Issue by sodabrew** [rybakit/msgpack.php#28] opened 2018-12-10 18:27 UTC
Hi! I'm trying to move a PR forward on the msgpack PHP C extension. Are you in touch with msgpack overall project management to help run this down? https://github.com/msgpack/msgpack-php/pull/124

Is the community recommending a move away from the C module and towards this one natively in PHP now?

**Comment by rybakit** [comment] 2018-12-11 13:32
Hi @sodabrew. Sorry, I have no relation to the msgpack project and can't help with moving your PR forward :( 

Regarding the community recommendations, this library was burn because of various issues and limitations I ran into while using the pecl extension and I tried to address them in my own implementation. Indeed, the official PHP extension seems not maintained anymore, but I'm not aware of any published recommendations regarding moving away from pecl towards my library.

**Comment by sodabrew** [comment] 2018-12-11 13:43
Thanks for the background info! So I'll describe my use case and let's see what we can do.

I maintain the php-mecached module. It supports using several different encoders transparently by setting the `flags` value of the memcached item. The three encoders currently supported are PHP Serialize, IgBinary, and MesssagePack via the msgpack-php C extension.

All three of these are C-based options.

I haven't given much thought to PHP-callback serializers. But I figure that should be pretty straightforward with this module, pass in a variable and get back a binary string?

**Comment by rybakit** [comment] 2018-12-11 13:53
>  But I figure that should be pretty straightforward with this module, pass in a variable and get back a binary string?

Correct, it should work for all data types except objects. To be able to serialize objects you have to implement your own [type transformer](https://github.com/rybakit/msgpack.php#type-transformers).

**Comment by rybakit** [comment] 2018-12-22 23:59
Closing as the issue is not related to msgpack.php.

**Closed as completed by rybakit** 2018-12-22 23:59 UTC
